{
gStyle->SetOptStat(0);
gStyle->SetPalette(1);
gStyle->SetPadRightMargin(0.15);

TFile f("CalMomP7.root");

TCut cut   = "DirPsf < 45 && CovPsf < 45 && ChiSq_mom > 0 && ChiSq_mom < 10 && NumCoreXtals_mom > 10";
TCut cut01 = "DirPsf < 45 && CovPsf < 45 && ChiSq_mom > 0 && ChiSq_mom < 10 && NumCoreXtals_mom > 10 && CalFullLen_mom < 1";
TCut cut12 = "DirPsf < 45 && CovPsf < 45 && ChiSq_mom > 0 && ChiSq_mom < 10 && NumCoreXtals_mom > 10 && CalFullLen_mom > 1 && CalFullLen_mom < 2";
TCut cut23 = "DirPsf < 45 && CovPsf < 45 && ChiSq_mom > 0 && ChiSq_mom < 10 && NumCoreXtals_mom > 10 && CalFullLen_mom > 2 && CalFullLen_mom < 3";
TCut cut34 = "DirPsf < 45 && CovPsf < 45 && ChiSq_mom > 0 && ChiSq_mom < 10 && NumCoreXtals_mom > 10 && CalFullLen_mom > 3";

    const Int_t NRGBs = 5;
    const Int_t NCont = 255;

    Double_t stops[NRGBs] = { 0.00, 0.34, 0.61, 0.84, 1.00 };
    Double_t red[NRGBs]   = { 0.00, 0.00, 0.87, 1.00, 0.51 };
    Double_t green[NRGBs] = { 0.00, 0.81, 1.00, 0.20, 0.00 };
    Double_t blue[NRGBs]  = { 0.51, 1.00, 0.12, 0.00, 0.00 };
    TColor::CreateGradientColorTable(NRGBs, stops, red, green, blue, NCont);
    gStyle->SetNumberContours(NCont);

Float_t stepSize = .15/3;
Float_t xMax = 6;
Float_t xMin = 3.5;
Float_t yMax = 3;
Float_t yMin = 0;
Float_t binX = (xMax - xMin)/stepSize;
Float_t binY = (yMax - yMin)/stepSize;
cout << binX << " " << binY << endl;

TH2F *hist = new TH2F("hist","hist",binX,xMin,xMax,binY,yMin,yMax);
newtree->Draw("log10(CalEnergyRaw/(McCharge**2*CalFullLen_mom*171.5)):log10(McEnergy/(2*McCharge))>>hist",cut);
hist->SetTitle("Incident MC Energy vs Energy Deposited per Pathlength");
hist->SetXTitle("Incident MC Energy/nucleon [MeV/amu]");
//hist->SetYTitle("Deposited Energy per Pathlength [MeV Z^{-2} cm^{2}/g]");
hist->SetYTitle("Deposited Energy per Pathlength [MeV Z^{-2} g^{-1} cm^{2}]");
hist->Draw("colz");
hist->GetXaxis()->SetLabelSize(0);
hist->GetXaxis()->SetTickLength(0);
hist->GetYaxis()->SetLabelSize(0);
hist->GetYaxis()->SetTickLength(0);
hist->GetXaxis()->SetTitleOffset(1.4);
hist->GetYaxis()->SetTitleOffset(1.4);
TGaxis *axis2 = new TGaxis(xMin,yMin,xMax,yMin,10**xMin,10**xMax,510,"G");
axis2->SetName("axis2");
axis2->SetLabelSize(0.035);
axis2->SetLabelFont(42);
axis2->Draw();
TGaxis *axis4 = new TGaxis(xMin,yMin,xMin,yMax,10**yMin,10**yMax,50510,"G");
axis4->SetName("axis4");
axis4->SetLabelSize(0.035);
axis4->SetLabelFont(42);
axis4->Draw();
c1.Update();
text = new TText(3.75,2.75,"Preliminary");
text.SetTextColor(2);
pal = (TPaletteAxis*)hist->GetListOfFunctions()->FindObject("palette");
pal->GetAxis()->SetTitle("Events");       
pal->GetAxis()->SetTitleOffset(1.4);
hist->SetMinimum(0);
text->Draw();
gPad->SetLogz(0);
c1->SaveAs("CalEnergyRaw-CalFullLen_mom.pdf");
c1->SaveAs("CalEnergyRaw-CalFullLen_mom.png");
gPad->SetLogz(0);
hist.Delete();

TH2F *hist = new TH2F("hist","hist",binX,xMin,xMax,binY,yMin,yMax);
newtree->Draw("log10(CalEnergyRaw/(McCharge**2*CalFullLen_mom*171.5)):log10(McEnergy/(2*McCharge))>>hist",cut01);
hist->SetTitle("Incident MC Energy vs Energy Deposited per Pathlength");
hist->SetXTitle("Incident MC Energy/nucleon [MeV/amu]");
//hist->SetYTitle("Deposited Energy per Pathlength [MeV Z^{-2} cm^{2}/g]");
hist->SetYTitle("Deposited Energy per Pathlength [MeV Z^{-2} g^{-1} cm^{2}]");
hist->Draw("colz");
hist->GetXaxis()->SetLabelSize(0);
hist->GetXaxis()->SetTickLength(0);
hist->GetYaxis()->SetLabelSize(0);
hist->GetYaxis()->SetTickLength(0);
hist->GetXaxis()->SetTitleOffset(1.4);
hist->GetYaxis()->SetTitleOffset(1.4);
TGaxis *axis2 = new TGaxis(xMin,yMin,xMax,yMin,10**xMin,10**xMax,510,"G");
axis2->SetName("axis2");
axis2->SetLabelSize(0.035);
axis2->SetLabelFont(42);
axis2->Draw();
TGaxis *axis4 = new TGaxis(xMin,yMin,xMin,yMax,10**yMin,10**yMax,50510,"G");
axis4->SetName("axis4");
axis4->SetLabelSize(0.035);
axis4->SetLabelFont(42);
axis4->Draw();
c1.Update();
text = new TText(3.75,2.75,"Preliminary");
text.SetTextColor(2);
pal = (TPaletteAxis*)hist->GetListOfFunctions()->FindObject("palette");
pal->GetAxis()->SetTitle("Events");       
pal->GetAxis()->SetTitleOffset(1.4);
hist->SetMinimum(0);
text->Draw();
gPad->SetLogz(0);
c1->SaveAs("CalEnergyRaw-CalFullLen_mom01.pdf");
c1->SaveAs("CalEnergyRaw-CalFullLen_mom01.png");
gPad->SetLogz(0);
hist.Delete();

TH2F *hist = new TH2F("hist","hist",binX,xMin,xMax,binY,yMin,yMax);
newtree->Draw("log10(CalEnergyRaw/(McCharge**2*CalFullLen_mom*171.5)):log10(McEnergy/(2*McCharge))>>hist",cut12);
hist->SetTitle("Incident MC Energy vs Energy Deposited per Pathlength");
hist->SetXTitle("Incident MC Energy/nucleon [MeV/amu]");
//hist->SetYTitle("Deposited Energy per Pathlength [MeV Z^{-2} cm^{2}/g]");
hist->SetYTitle("Deposited Energy per Pathlength [MeV Z^{-2} g^{-1} cm^{2}]");
hist->Draw("colz");
hist->GetXaxis()->SetLabelSize(0);
hist->GetXaxis()->SetTickLength(0);
hist->GetYaxis()->SetLabelSize(0);
hist->GetYaxis()->SetTickLength(0);
hist->GetXaxis()->SetTitleOffset(1.4);
hist->GetYaxis()->SetTitleOffset(1.4);
TGaxis *axis2 = new TGaxis(xMin,yMin,xMax,yMin,10**xMin,10**xMax,510,"G");
axis2->SetName("axis2");
axis2->SetLabelSize(0.035);
axis2->SetLabelFont(42);
axis2->Draw();
TGaxis *axis4 = new TGaxis(xMin,yMin,xMin,yMax,10**yMin,10**yMax,50510,"G");
axis4->SetName("axis4");
axis4->SetLabelSize(0.035);
axis4->SetLabelFont(42);
axis4->Draw();
c1.Update();
text = new TText(3.75,2.75,"Preliminary");
text.SetTextColor(2);
pal = (TPaletteAxis*)hist->GetListOfFunctions()->FindObject("palette");
pal->GetAxis()->SetTitle("Events");       
pal->GetAxis()->SetTitleOffset(1.4);
hist->SetMinimum(0);
text->Draw();
gPad->SetLogz(0);
c1->SaveAs("CalEnergyRaw-CalFullLen_mom12.pdf");
c1->SaveAs("CalEnergyRaw-CalFullLen_mom12.png");
gPad->SetLogz(0);
hist.Delete();

TH2F *hist = new TH2F("hist","hist",binX,xMin,xMax,binY,yMin,yMax);
newtree->Draw("log10(CalEnergyRaw/(McCharge**2*CalFullLen_mom*171.5)):log10(McEnergy/(2*McCharge))>>hist",cut23);
hist->SetTitle("Incident MC Energy vs Energy Deposited per Pathlength");
hist->SetXTitle("Incident MC Energy/nucleon [MeV/amu]");
//hist->SetYTitle("Deposited Energy per Pathlength [MeV Z^{-2} cm^{2}/g]");
hist->SetYTitle("Deposited Energy per Pathlength [MeV Z^{-2} g^{-1} cm^{2}]");
hist->Draw("colz");
hist->GetXaxis()->SetLabelSize(0);
hist->GetXaxis()->SetTickLength(0);
hist->GetYaxis()->SetLabelSize(0);
hist->GetYaxis()->SetTickLength(0);
hist->GetXaxis()->SetTitleOffset(1.4);
hist->GetYaxis()->SetTitleOffset(1.4);
TGaxis *axis2 = new TGaxis(xMin,yMin,xMax,yMin,10**xMin,10**xMax,510,"G");
axis2->SetName("axis2");
axis2->SetLabelSize(0.035);
axis2->SetLabelFont(42);
axis2->Draw();
TGaxis *axis4 = new TGaxis(xMin,yMin,xMin,yMax,10**yMin,10**yMax,50510,"G");
axis4->SetName("axis4");
axis4->SetLabelSize(0.035);
axis4->SetLabelFont(42);
axis4->Draw();
c1.Update();
text = new TText(3.75,2.75,"Preliminary");
text.SetTextColor(2);
pal = (TPaletteAxis*)hist->GetListOfFunctions()->FindObject("palette");
pal->GetAxis()->SetTitle("Events");       
pal->GetAxis()->SetTitleOffset(1.4);
hist->SetMinimum(0);
text->Draw();
gPad->SetLogz(0);
c1->SaveAs("CalEnergyRaw-CalFullLen_mom23.pdf");
c1->SaveAs("CalEnergyRaw-CalFullLen_mom23.png");
gPad->SetLogz(0);
hist.Delete();


TH2F *hist = new TH2F("hist","hist",binX,xMin,xMax,binY,yMin,yMax);
newtree->Draw("log10(CalEnergyRaw/(McCharge**2*CalFullLen_mom*171.5)):log10(McEnergy/(2*McCharge))>>hist",cut34);
hist->SetTitle("Incident MC Energy vs Energy Deposited per Pathlength");
hist->SetXTitle("Incident MC Energy/nucleon [MeV/amu]");
//hist->SetYTitle("Deposited Energy per Pathlength [MeV Z^{-2} cm^{2}/g]");
hist->SetYTitle("Deposited Energy per Pathlength [MeV Z^{-2} g^{-1} cm^{2}]");
hist->Draw("colz");
hist->GetXaxis()->SetLabelSize(0);
hist->GetXaxis()->SetTickLength(0);
hist->GetYaxis()->SetLabelSize(0);
hist->GetYaxis()->SetTickLength(0);
hist->GetXaxis()->SetTitleOffset(1.4);
hist->GetYaxis()->SetTitleOffset(1.4);
TGaxis *axis2 = new TGaxis(xMin,yMin,xMax,yMin,10**xMin,10**xMax,510,"G");
axis2->SetName("axis2");
axis2->SetLabelSize(0.035);
axis2->SetLabelFont(42);
axis2->Draw();
TGaxis *axis4 = new TGaxis(xMin,yMin,xMin,yMax,10**yMin,10**yMax,50510,"G");
axis4->SetName("axis4");
axis4->SetLabelSize(0.035);
axis4->SetLabelFont(42);
axis4->Draw();
c1.Update();
text = new TText(3.75,2.75,"Preliminary");
text.SetTextColor(2);
pal = (TPaletteAxis*)hist->GetListOfFunctions()->FindObject("palette");
pal->GetAxis()->SetTitle("Events");       
pal->GetAxis()->SetTitleOffset(1.4);
hist->SetMinimum(0);
text->Draw();
gPad->SetLogz(0);
c1->SaveAs("CalEnergyRaw-CalFullLen_mom34.pdf");
c1->SaveAs("CalEnergyRaw-CalFullLen_mom34.png");
gPad->SetLogz(0);
hist.Delete();

}
